### ISSUE TITLE
AlphaVantageRequestHandler not found

### ISSUE THREAD

**Issue by tafensw2810** [swar8080/FastStockQuotes#1]
Hi,

Thanks for this library, I am hoping it will really help me out!

I have run through and installed via composer.  When I try and run your demo, I get the following error:

Fatal error: Uncaught Error: Class 'FastStockQuotes\QuoteAPIs\AlphaVantageRequestHandler' not found in /var/www/html/webroot/testing/faststockquotes/vendor/swar8080/fast-stock-quotes/src/FastQuoteServiceBuilder.php:72 Stack trace: #0 /var/www/html/webroot/testing/faststockquotes/index.php(15): FastStockQuotes\FastQuoteServiceBuilder->withAlphaVantageGlobalQuoteAPI('MFA29WKOP6FCNRO...') #1 {main} thrown in /var/www/html/webroot/testing/faststockquotes/vendor/swar8080/fast-stock-quotes/src/FastQuoteServiceBuilder.php on line 72

Any ideas?

Thank you! :)

**Comment by swar8080** [comment]
Hey, I'm glad to see this library is (potentially) useful for you.

I noticed that the latest github version wasn't in sync with the packagist code that your composer would've pulled from. Now that it's in sync, removing and re-installing the library with `composer require swar8080/fast-stock-quotes` might just fix it.

If that doesn't fix it, the error suggests that an expected file at `/var/www/html/webroot/testing/faststockquotes/vendor/swar8080/fast-stock-quotes/src/quoteAPIs/AlphaVantageRequestHandler.php` couldn't be found.

When testing the demo with a clean install I couldn't reproduce the issue. Were there any changes made to the composer project after installing the library?
