### ISSUE TITLE
Array of tickers

### ISSUE THREAD

**Issue by Maggern** [swar8080/FastStockQuotes#2]
Hi!

Hi! Thanks for this nice project. I'm having problems with sending in an array of tickers into $quotes. 

Var_dump:
array (size=7)
  0 => string 'AXAO.ST' (length=7)
  1 => string 'AXA.OL' (length=6)
  2 => string 'BWO.OL' (length=6)
  3 => string 'EKO.OL' (length=6)
  4 => string 'ELE.OL' (length=6)
  5 => string 'FUNCOM.OL' (length=9)
  6 => string 'NANO.OL' (length=7)

I've added OL/ST stock code and country. When I do one and one ticker with
$quotes = $quoteService->quotes(StockSymbol::Symbols('EKO.OL'));
it works. 

How do I push an array correctly?

**Comment by swar8080** [comment]
Hey,

The `quotes()` function takes an array of `StockSymbol` objects as its parameter.

You can create each stock symbol object in the array like this:

```'
$symbolObjectArray = [
   new StockSymbol('AXAO.ST'),
   new StockSymbol('AXA.OL'),
   new StockSymbol('BWO.OL')
];

$quotes = $quoteService->quotes($symbolObjectArray);
```

Or you can use the `StockSymbol::Symbols` function to create the `StockSymbol` array more conveniently:

```
$symbolObjectArray = StockSymbol::Symbols('AXAO.ST', 'AXA.OL', 'BWO.OL');
$quotes = $quoteService->quotes($symbolObjectArray);
``` 
Also, I just added support for Swedish and Norwegian stocks. You'll need to run `composer require swar8080/fast-stock-quotes` to get the updated code. If there are other countries you'd like quotes for that aren't already configured, you can use [my recent commit](https://github.com/swar8080/FastStockQuotes/commit/3608e96aed36b1eaa0c3b21118d6daa95cb55fac) as an example of how to add them.

**Comment by Maggern** [comment]
Thanks for your help! I'm a little new to php. I solved my issue by doing this:

foreach ($tickers as $ticker) {
	$symbolObjectArray[] = new StockSymbol($ticker);
}
