### ISSUE TITLE
Turn off caching? 

### ISSUE THREAD

**Issue by Maggern** [swar8080/FastStockQuotes#3]
Hi! It says that caching with Redis is optional. How do I turn it off? 
(I'm having problems getting Redis to work on my server.)

**Comment by swar8080** [comment]
Hey, to create a `QuoteService` object that queries the API without using caching:
```
$quoteService = FastQuoteServiceBuilder::builder()
	->withAlphaVantageGlobalQuoteAPI("your API key")
	->build();
```

To create it with caching enabled:
```
$quoteService = FastQuoteServiceBuilder::builder()
	->withAlphaVantageGlobalQuoteAPI("your API key")
	->withRedisCaching(new \Predis\Client(), $minCachingLengthSeconds=300)
	->build();
```

The [demo code](https://github.com/swar8080/FastStockQuotes#demo) should explain how to use the `QuoteService` object from there.

**Comment by Maggern** [comment]
Thanks!
